# General
title:          César Ferradas
description:    Software Engineering, Business, Minimalism, Finance
url:            https://ferrad.as
baseurl:        ""

# Navigation
permalink:      /:slug

# Contact
author:
  name:         César
  github:       https://github.com/cesarferradas
  linkedin:     https://www.linkedin.com/in/cesarferradas

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
