# General
title:          César Ferradas
description:    Software Engineering, Business, Minimalism, Finance
url:            https://ferrad.as
baseurl:        ""

# Navigation
permalink:      /:slug

# Minify CSS
sass:
  style: compressed

# Contact
author:
  name:         César Ferradas
  github:       https://github.com/cesarferradas
  linkedin:     https://www.linkedin.com/in/cesarferradas

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap

highlighter: rouge

exclude:
  - new_post.sh
