# General
title:          César Ferradas
description:    Software Engineering, Business, Minimalism, Finance
url:            https://ferrad.as
baseurl:        ""

# Navigation
permalink:      /:slug

# Minify CSS
sass:
  style: compressed
  sourcemap: never

# Contact
author:
  name: César Ferradas
  contacts:
    - name: GitHub
      url: https://github.com/cesarferradas
      handle: cesarferradas
    - name: LinkedIn
      url: https://www.linkedin.com/in/cesarferradas
      handle: César Ferradas
    - name: Hacker News
      url: https://news.ycombinator.com/user?id=ferradas
      handle: ferradas

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap

highlighter: rouge

exclude:
  - new_post.sh
